[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
axum = "0.8.1"
dotenv = "0.15.0"
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
